### ISSUE TITLE
Checkpoint loading not working

### ISSUE THREAD

**Issue by jhbastek** [plemeri/transparent-background#1]
Looks very neat, thanks for sharing!
Could you confirm that the [link](https://postechackr-my.sharepoint.com/:u:/g/personal/taehoon1018_postech_ac_kr/ET0R-yM8MfVHqI4g94AlL6AB-D6LxNajaWeDV4xbVQyh7w\?e\=l4JkZn\&download\=1) to download the latest model checkpoint is indeed working as supposed to? 
I cannot get it to download anything (but also had to change some things in the code since I am running on Windows and not sure if that broke something).
Thanks in advance!

**Comment by plemeri** [comment]
Hi, thank you for your attention!

Actually we didn't tested our package on windows, so it might not work for your environment. Could you give me some time to test on my local windows machine to confirm which makes the problem?

**Comment by plemeri** [comment]
Also, the download link is made for `wget` command, so the valid link for web browser is this [Link](https://postechackr-my.sharepoint.com/:u:/g/personal/taehoon1018_postech_ac_kr/ET0R-yM8MfVHqI4g94AlL6AB-D6LxNajaWeDV4xbVQyh7w?e=l4JkZn). Hope this temporarily works!

**Comment by jhbastek** [comment]
Great -- it works now. Just as a minor suggestion: It might be great if you could adjust the framework to work without issues on Windows environments. The issues are in line 33 (changed 'HOME' to e.g., 'USERPROFILE') and the download_and_unzip function that uses some Linux command line arguments.

**Comment by plemeri** [comment]
Awesome! Thank you for your suggestion, I really appreciate it.

**Comment by plemeri** [comment]
We just resolved some issues on windows thanks to your advice. Related commit is [9b9e9e5](https://github.com/plemeri/transparent-background/commit/9b9e9e5d3e09ff2231745e051323ff5ab30841c0). We also updated pypi version to 1.0.3 so please check that out as well.

**Comment by mhashas** [comment]
I'm hijacking this PR. First of all, thanks for the great work! Second of all, do you think you can add the checkpoint dir as a command line argument, so we can load it from a local path if we download it ourselves. That would be great. If not given, it can just default to the current path

**Comment by plemeri** [comment]
> I'm hijacking this PR. First of all, thanks for the great work! Second of all, do you think you can add the checkpoint dir as a command line argument, so we can load it from a local path if we download it ourselves. That would be great. If not given, it can just default to the current path

Sounds wonderful! Now I'm currently planning to support a fast-compute mode by using another checkpoint trained with LR scale. I'll add checkpoint selection functionality as well for the update.

Thanks for your advice!

**Comment by plemeri** [comment]
> I'm hijacking this PR. First of all, thanks for the great work! Second of all, do you think you can add the checkpoint dir as a command line argument, so we can load it from a local path if we download it ourselves. That would be great. If not given, it can just default to the current path

I just uploaded `1.2.1` version which now supports using other checkpoints. 
Thanks.
