### ISSUE TITLE
Are Plus_Ultra weights pointing at Base weights???

### ISSUE THREAD

**Issue by mike-silver-Crafty-Apes-VFX** [plemeri/transparent-background#11]
The Base weights as seen in Remover.py can be found at this url:
https://drive.google.com/file/d/13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY/view?usp=share_link

Plus_Ultra can be downloaded at the Model Zoo link provided in the repo (https://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md)

However, the Plus_Ultra link is pointing here -- which is the same link as Base:
https://drive.google.com/file/d/13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY/view

Is this an error? Thanks.

**Comment by plemeri** [comment]
Hi, there's an issue related to the url in the original repository [plemeri/InSPyReNet#24](https://github.com/plemeri/InSPyReNet/issues/24). I'm trying to fix this issue. 

Thank you.

**Comment by plemeri** [comment]
We fixed the issue related to the url. Also, sorry for the late response but this repository is for general purpose, not for the academic evaluation, and for the best performance for the real-world scenarios, we use the checkpoint trained with all SOD datasets which are available in public. 

Long story short, Base pointing Plus_Ultra is not an error, we intended to do so.
Thank you.
