### ISSUE TITLE
Fast conversion to Onnx

### ISSUE THREAD

**Issue by rhysdg** [plemeri/transparent-background#13]
Hey there I'm getting a floating point error  while converting to onnx with torch 2.0.1 - Is there a specific method that was used to convert to the onnx representation? I see that there's a base 1024 IR available but I'd love to get my hands on a working 384 conversion!

Thanks for your help in advance!

**Comment by oylz** [comment]
* 1.export 384 resolution model ([Plus_Ultra_LR](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra_LR.yaml)) to onnx may throw a **floating pointer exception**, this is a torch bug, in the function **ComputeShapeFromReshape**, [crash at this line](https://github.com/pytorch/pytorch/blob/main/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L493)
```
      if (shape_ratio >=
          std::numeric_limits<uint64_t>::max() / input_shape.static_size()) {
```

* 2.I have fixed this bug local, and convert 384 resolution model ([Plus_Ultra_LR](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra_LR.yaml)) to onnx, and I shared it on google drive, you can [download](https://drive.google.com/file/d/1oP81po6ml6xh4eyt-YgKpofstQ1-dvjU/view?usp=drive_lin)

* 3.TODO: **I will push a PR to pytorch**

**Comment by plemeri** [comment]
Thank you for dealing with the problem @oylz. I really appreciate it since I'm currently busy at this moment.

**Comment by rhysdg** [comment]
> @rhysdg
> 
> * 1.export 384 resolution model ([Plus_Ultra_LR](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra_LR.yaml)) to onnx may throw a **floating pointer exception**, this is a torch bug, in the function **ComputeShapeFromReshape**, [crash at this line](https://github.com/pytorch/pytorch/blob/main/torch/csrc/jit/passes/onnx/shape_type_inference.cpp#L493)
> 
> ```
>       if (shape_ratio >=
>           std::numeric_limits<uint64_t>::max() / input_shape.static_size()) {
> ```
> 
> * 2.I have fixed this bug local, and convert 384 resolution model ([Plus_Ultra_LR](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra_LR.yaml)) to onnx, and I shared it on google drive, you can [download](https://drive.google.com/file/d/1oP81po6ml6xh4eyt-YgKpofstQ1-dvjU/view?usp=drive_lin)
> * 3.TODO: **I will push a PR to pytorch**

Wonderful! Thanks for the detailed explanation and the solve @oylz

**Comment by oylz** [comment]
> @oylz Downloading requires permission, cannot download, request repair!
> 
> ```
> https://drive.google.com/file/d/1oP81po6ml6xh4eyt-YgKpofstQ1-dvjU/view?usp=drive_lin
> ```

ok now with you
