### ISSUE TITLE
Two ideas for InSPyReNet

### ISSUE THREAD

**Issue by sanghyun0927** [plemeri/transparent-background#16]
1. Fast inference
Triton inference server cost about 1 sec for InSPyReNet

2. Text based segmentation.
Make a pipeline with object detection model, such as GoundingDINO, which is what langSAM had done.

**Comment by happyeungin** [comment]
Fast inference is very important. it is taking so long now.

**Comment by plemeri** [comment]
Thank you for the suggestions. I agree with the fact that fast inference is important. However, currently InSPyReNet is developed for the best quality not for the best inference speed.

If you have interested in model conversion in ONNX or using Triton server, I would like to collaborate with other developers so feel free to contact me about this issue. 

Thank you.
