### ISSUE TITLE
How to make inference faster with GPU?

### ISSUE THREAD

**Issue by BingliangLi** [plemeri/transparent-background#17]
Hi, thank you very much for this great tool.

I'm having some trouble with the video inference speed, a 1080p video of 5 min takes about 20 min to process with A100 80G GPU(fast mode, no jit). Is there a way I can speed this up by using multiple GPUs? Or is there a way to increase batch size or number of workers?

Thanks!

```bash
(seg) root@e689d2c30a8f:/workspace# transparent-background --source test_9.mp4 --type white --ckpt /workspace/checkpoints/transparent-background/latest_LR.pth --fast                                                                                                                                   
Settings -> Mode=fast, Device=cuda:0, Torchscript=disabled
test_9.mp4:     77%|██████████████████████████████████████▍           | 7051/9185 [15:21<04:35,  7.73it/s]
```

**Comment by plemeri** [comment]
For high quality mask prediction, there is no choice but to take long time for large images. You can simply use ``--fast`` argument to speed up the inference time but it will produce lower quality results.
