### ISSUE TITLE
The latest.pth from google drive

### ISSUE THREAD

**Issue by happyeungin** [plemeri/transparent-background#19]
Access denied with the following error:

 	Too many users have viewed or downloaded this file recently. Please
	try accessing the file again later. If the file you are trying to
	access is particularly large or is shared with many people, it may
	take up to 24 hours to be able to view or download the file. If you
	still can't access a file after 24 hours, contact your domain
	administrator.

**Comment by plemeri** [comment]
Maybe there are some download limit issue for the google drive. You can download checkpoint from other channel which can be found in our original repository [InSPyReNet[(https://github.com/plemeri/InSPyReNet). Specifically, the checkpoint that you might have been looking for can be found in this [alternative link](https://postechackr-my.sharepoint.com/:u:/g/personal/taehoon1018_postech_ac_kr/ET0R-yM8MfVHqI4g94AlL6AB-D6LxNajaWeDV4xbVQyh7w?e=l4JkZn).

**Comment by happyeungin** [comment]
@plemeri thanks.

Is there a way to update the pip package so it won't download from google drive? It is very annoying it is always downloading from google drive and it is not working..

**Comment by phoppe93** [comment]
i have the same issue, can someone help here ?

**Comment by happyeungin** [comment]
> i have the same issue, can someone help here ?

hopefully the team can update the download URL to somewhere stable.. Google Drive is always dead now

**Comment by phoppe93** [comment]
@plemeri is it possible to upload it somewhere else ? I try to find a workaround, but it seems that the google url is hardcoded

**Comment by phoppe93** [comment]
@happyeungin download works now !!!

**Comment by plemeri** [comment]
Sorry for the inconvenience. I didn't expect that Google drive cannot handle the traffic.

Here's an alternative link for downloading checkpoint. Try download from this [url](https://postechackr-my.sharepoint.com/:f:/g/personal/taehoon1018_postech_ac_kr/Erned6ivc3pPkX-tRBOmh_oBDoAC46ZfhAT0U_PnYPDX_Q?e=sjW8Eu)

**Comment by happyeungin** [comment]
> Sorry for the inconvenience. I didn't expect that Google drive cannot handle the traffic.
> 
> 
> 
> Here's an alternative link for downloading checkpoint. Try download from this [url](https://postechackr-my.sharepoint.com/:f:/g/personal/taehoon1018_postech_ac_kr/Erned6ivc3pPkX-tRBOmh_oBDoAC46ZfhAT0U_PnYPDX_Q?e=sjW8Eu)

It could be more people are using now. 

Can we have an option to switch the default google drive URL?

I uploaded the .pth to my own google drive so it won't be affected, but I have no way to switch the URL.

**Comment by helmutkaufmann** [comment]
The problem is that the current Python scripts checks for the MD5 hash, which is hard-coded in the script. As the hash value is hard-coded in the script, it repeatedly downloads latest.pth - which is unnecessary.

**Comment by erisvulgaris** [comment]
Is there any method so that I can skip the file downloading and use the file which is already downloaded?

**Comment by plemeri** [comment]
Thank you all for your patience! I just updated the latest release with various options related to the checkpoint download methods. Please check readme update messages.

Cheers!
