### ISSUE TITLE
The result doesn't look good

### ISSUE THREAD

**Issue by babyta** [plemeri/transparent-background#20]
![output](https://github.com/plemeri/transparent-background/assets/37787795/4a86e305-b1d4-4776-9ef2-777a37e3283b)
The inference output results seem to have blurred borders. Is there any post-processing required?

**Comment by plemeri** [comment]
This is not the expected output. There are some possibilities that might cause the problem.

1. Invalid trained checkpoint - Try download from this [url](https://postechackr-my.sharepoint.com/:f:/g/personal/taehoon1018_postech_ac_kr/Erned6ivc3pPkX-tRBOmh_oBDoAC46ZfhAT0U_PnYPDX_Q?e=sjW8Eu)
2. unexpected image size

**Comment by babyta** [comment]
ok,thank you
