### ISSUE TITLE
Can you add a threshold parameter to adjust the strength of reasoning?

### ISSUE THREAD

**Issue by huchang47** [plemeri/transparent-background#22]
In practical image processing, there are situations where objects in the foreground or those too close to the subject are mistakenly identified and outputted. By experimentally adjusting the intensity threshold, this issue can theoretically be resolved.

**Comment by plemeri** [comment]
Sure thing. Also, you can do on your branch and generate a pull request if you want.

**Comment by plemeri** [comment]
Thresholding output result is now supported. Please check the latest release. Thanks!
