### ISSUE TITLE
[Discussion] Information about varying resolutions input

### ISSUE THREAD

**Issue by SuperSecureHuman** [plemeri/transparent-background#27]
I see in the readme

`Our package is currently not working properly on small images without --fast argument. Sorry for the inconvenience and we'll fix this issue with better algorithm coming out shortly.`

How do you do this?

How do you model it in such a way that it works on low res, and high res images?

Any different way of training?

Also, how much effect does resolution in gernal have in this particaular architure?

**Comment by SuperSecureHuman** [comment]
Thanks for this comment!

I will try out the new checkpoint on my use case, and tell about the results.

**Comment by plemeri** [comment]
Closing the issue due to inactivity.
