### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (512,512,4) (3,) (512,512,4) 

### ISSUE THREAD

**Issue by ilikewebsite** [plemeri/transparent-background#3]
ValueError: operands could not be broadcast together with shapes (512,512,4) (3,) (512,512,4)

**Comment by plemeri** [comment]
Hi, can you tell me how to reproduce the error?

**Comment by ilikewebsite** [comment]
Use png image as input instead of jpeg you will get error, It should take both png and jpeg

**Comment by plemeri** [comment]
> 

Thanks for the quick reply. Can you send me the image you used via e-mail? the address is taehoon1018@postech.ac.kr

**Comment by plemeri** [comment]
Unfortunately, I cannot reproduce the error. Here are the results for every option we provide.

new bg | blur | green | map | overlay | rgba
:-:|:-:|:-:|:-:|:-:|:-:|
![my-design (6)_background](https://user-images.githubusercontent.com/40786892/204947784-6848b95b-c410-4251-b9df-e71fce942e9f.png) | ![my-design (6)_blur](https://user-images.githubusercontent.com/40786892/204947793-915c2b43-7f06-44c1-aa01-5d4fc7d69a49.png) | ![my-design (6)_green](https://user-images.githubusercontent.com/40786892/204947795-f6686bca-0946-4d48-81e1-d1eba52a4e9c.png) | ![my-design (6)_map](https://user-images.githubusercontent.com/40786892/204947802-e005b21d-5837-4f54-92f0-0a2f012050b4.png) | ![my-design (6)_overlay](https://user-images.githubusercontent.com/40786892/204947804-32a07053-08ef-455e-b773-b325746aab6e.png) | ![my-design (6)_rgba](https://user-images.githubusercontent.com/40786892/204947805-8bd42e83-afa9-4003-8432-0162bee26313.png)

Did you try installing our latest version? Currently it is 1.1.3. If so, could you tell me which command did you use if you used command-line or script if you used our API?

**Comment by ilikewebsite** [comment]
It's issue with api

**Comment by plemeri** [comment]
> It's issue with api

Can you tell me the whole script you used to reproduce the error?

**Comment by ilikewebsite** [comment]
It's same as you have documented

**Comment by ilikewebsite** [comment]
Done ! Thanks

**Comment by plemeri** [comment]
> Done ! Thanks

Awesome, have a great day!
