### ISSUE TITLE
error when jit == True, version 1.2.4

### ISSUE THREAD

**Issue by gef12** [plemeri/transparent-background#33]
error when jit == True,  traced_model = torch.jit.trace(self.model, torch.rand(1, 3, *self.meta['base_size']).to(self.device), strict=True)

![image](https://github.com/plemeri/transparent-background/assets/22777207/05ebd58a-54b4-425d-8d43-0cecfde29b0e)

OS Windows 11
Python 3.11.5
pytorch 2.0.1 Cuda 11.8

I may have missed something, I'm creating UI for my use
![image](https://github.com/plemeri/transparent-background/assets/22777207/3ff1f13e-58fc-409e-a224-4102c94f07c4)

**Comment by plemeri** [comment]
This is not an error related to our package. It's a common error related to the GPU memory.

**Comment by gef12** [comment]
Thanks for responding, could you tell me how much vram is needed to activate the JIT version?
video card used was a 3060ti 8gb vram
