### ISSUE TITLE
operands could not be broadcast together with shapes (960,720,3) (953,715,1)

### ISSUE THREAD

**Issue by j-dbooth** [plemeri/transparent-background#36]
When using  
`
def process_images_in_folder(folder_path, background_image_paths):
    #? Load model
    remover = Remover(ckpt='C:\\Users\\James\\.transparent-background\\ckpt_base.pth')
    #? Get a list of JPG files in the folder
    jpg_files = [f for f in os.listdir(folder_path) if f.lower().endswith('.jpg')]
    #? Process each JPG image in the folder with each background
    for jpg_file in jpg_files:
        #? Construct the full path to the image
        image_path = os.path.join(folder_path, jpg_file)
        #? Open the image and convert it to RGB format
        img = Image.open(image_path).convert('RGB')
        try:
            #? Process the image with each background image 1
            out = remover.process(img, type=background_image_paths)
            #? Save the processed image with a new name
            output_path = os.path.join(folder_path, f'output_{jpg_file}_{os.path.basename(background_image_paths)}.png')
            out.save(output_path)
        except Exception as e:
                print(f"Error processing {jpg_file} with background: {background_image_paths}")
                print(f"Error message: {e}")
                #? Delete the bad image
                os.remove(image_path)
    print("Finished processing all images with different backgrounds.")

`
It says "Error processing ghost-stand2.jpg with background: samples\background1.jpg
Error message: operands could not be broadcast together with shapes (960,720,3) (953,715,1)"
Im thinking this is due to SampleImage1 having a resolution of (960,720) while SampleImage2 has (953,715) but im unsure as to why its causing problems and/or how to fix it currently

Test Photos in use can be found attached Below

Full terminal output :: 
C:\Users\James>python ImageEngine.py "C:\Users\James\Ghost Booh Stand" 1
C:\Python310\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Settings -> Mode=base, Device=cpu, Torchscript=disabled
Error processing ghost-stand2.jpg with background: samples\background1.jpg
Error message: operands could not be broadcast together with shapes (960,720,3) (953,715,1)`
Sample1::
![ghost-stand1](https://github.com/plemeri/transparent-background/assets/71133794/74e9a0f2-d5a6-42e8-b301-a10a6d6483c8)
Sample2::
![ghost-stand2](https://github.com/plemeri/transparent-background/assets/71133794/91e0ec2c-b5a4-451a-9e73-6036f6d9f6a1)
Background1::
![background1](https://github.com/plemeri/transparent-background/assets/71133794/58017f59-eb04-4094-b6e0-1c190e7e12b2)

**Comment by plemeri** [comment]
Hi, @j-dbooth thank you for reporting a bug for us. We'll try fixing it. Until then, please use cli-tool instead which seems working on your samples.

**Comment by plemeri** [comment]
Hi, please check out for the new release. 

Let be briefly explain the error. Because we did not expect using same background for different image resolution, the background image was reused which had been already resized into the previous input. 

We fixed the issue by tracking the background image resolution, filename to deal with the new input. 

Thank you.

**Comment by wilfrediscoming** [comment]
@j-dbooth can you mark this as closed?

**Comment by plemeri** [comment]
Closing the issue. Please open another issue if this problem persists.

**Comment by j-dbooth** [comment]
> @j-dbooth can you mark this as closed?

It got closed ages ago?

**Comment by j-dbooth** [comment]
> @j-dbooth can you mark this as closed?

It was closed by Plemeri ages ago, was it not?
