### ISSUE TITLE
the new nightly checkpoint cannot provide similar result quality as the original chkpt

### ISSUE THREAD

**Issue by wilfrediscoming** [plemeri/transparent-background#38]
![case](https://github.com/plemeri/transparent-background/assets/137744070/e96cab2b-b3cd-4c7d-9a16-554d85a4e3c3)

Try this with the new chkpt, it only returns the camera portion.. But the original checkpoint can correctly remove the background and return the case.

The original checkpoint may still have a better accuracy.

**Comment by plemeri** [comment]
Thank you @wilfrediscoming for your report. I'll consider this problem for the future release.
