### ISSUE TITLE
Seeming inconsistency between `base_size` and resize value

### ISSUE THREAD

**Issue by niqodea** [plemeri/transparent-background#42]
Hi, thank you for your work! I was wondering why the base and nightly checkpoints have `base_size=1024` while the resize preprocessing of the image is `L=1280`. These values seem to match for the fast case (both are `384`).

**Comment by plemeri** [comment]
base_size is used when training a model. our SICA module in InSPyReNet needs this parameter for resizing. base model is trained with 1024 x 1024, while fast model is trained with 384 x 384. Also, for fast model, we resize the image into the same size for faster inference.

**Comment by niqodea** [comment]
Hi @plemeri, thank you for your answer! I am still wondering where the `L=1280` comes from. I tried changing it to `1024` and indeed I seem to be getting slightly better results.

Happy holidays to you as well!

**Comment by plemeri** [comment]
Hi @niqodea, L=1280 means that we use dynamic resizing. Here, 1280 means if one of the shorter side is larger than 1280, we resize the shorter side into 1280 and the other side as well by its ratio (e.g., 3840 x 2160 -> 2275 x 1280). 

We're also aware of the performance difference. Using static resize (1024 x 1024) shows better performance in terms of Smeasure, Fmeasure, which are related to the overall mask accuracy while dynamic resize (L=1280) brings better performance in terms of boundary accuracy. 

You can find more information in our paper. 
https://arxiv.org/abs/2209.09475

Thanks

**Comment by niqodea** [comment]
Thank you for the help and details!
