### ISSUE TITLE
Published package does not match tagged release

### ISSUE THREAD

**Issue by PeterJCLaw** [plemeri/transparent-background#50]
The GitHub release for 1.2.12 discusses the move from `gdown` to `wget` for some endpoints and indeed the source does have some related changes.

However the `setup.py` in the linked commit doesn't seem to mention `wget`. Even more so -- the latest `setup.py` in this repo claims to be at version 1.2.10 and not 1.2.12!

In contrast, the published `setup.py` in the source distribution does seem to be for 1.2.12 and does mention `wget`.

Are there some changes which haven't made it into this repo?
As a consumer of this package, while it is quite valuable as a library, it is quite disconcerting when the published package doesn't match the tagged source for that version.

**Comment by plemeri** [comment]
Sorry for the inconvenience. I'll resolve the issue ASAP. Thanks for the report.

**Comment by PeterJCLaw** [comment]
Thanks!
Would you be interested in a PR which added packaging & publishing via GitHub Actions? Automating those steps would make them more easily reproducible, less effort and make it much harder for the repo and the published package to get out of step.

**Comment by plemeri** [comment]
Sounds great but I cannot because I graduated last year and I barely have a time to maintain this project, so I could disappoint your great effort. If you still want to help with this, you are most welcome and sorry for the late reply.
