### ISSUE TITLE
Remove the background from the movie and makes it transparent

### ISSUE THREAD

**Issue by Hemilibeatriz** [plemeri/transparent-background#52]
Is it possible?

I tried with:

out = remover.process(img) # same as image, except for 'rgba' which is not for video.

I removed the 'type' argument because in the image it doesn't have one, but it still doesn't work.

**Comment by plemeri** [comment]
Hi @Hemilibeatriz , could you be more specific? I cannot understand the issue. The `type` argument has 6 different options.
![image](https://github.com/plemeri/transparent-background/assets/40786892/3ab1b558-1459-40d3-a8a0-4b0f6d1691c6)

**Comment by Hemilibeatriz** [comment]
An example:

```
import cv2
import numpy as np

from PIL import Image
from transparent_background import Remover

# Load model
remover = Remover() # default setting
remover = Remover(mode='fast', jit=True, device='cuda:0', ckpt='/root/.transparent-background/ckpt_base.pth') # custom setting
remover = Remover(mode='base-nightly') # nightly release checkpoint

# Usage for video
cap = cv2.VideoCapture('/content/Background.mp4') # video reader for input
fps = cap.get(cv2.CAP_PROP_FPS)

writer = None

while cap.isOpened():
    ret, frame = cap.read() # read video

    if ret is False:
        break
        
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) 
    img = Image.fromarray(frame).convert('RGB')

    if writer is None:
        writer = cv2.VideoWriter('output.mp4', cv2.VideoWriter_fourcc(*'mp4v'), fps, img.size) # video writer for output

    out = remover.process(img, type='*png') # same as image, except for 'rgba' which is not for video.
    writer.write(cv2.cvtColor(np.array(out), cv2.COLOR_BGR2RGB))

cap.release()
writer.release()
```

This code creates a movie without a transparent background. The background is white. What´s wrong? Can you help me?

**Comment by plemeri** [comment]
for `*.png` type, you need to specify a background image path such as `/home/user/background_sample.png`. Valid types for video output are `map`, `green`, `blur`, `overlay`, `*.png`. `rgba` won't work since there are no video format for rgba.

**Comment by Hemilibeatriz** [comment]
Where do I need to specify this? Can you tell me?

**Comment by plemeri** [comment]
In Line 30
```python
out = remover.process(img, type='*png')
```
Change this line to below.
```python
out = remover.process(img, type='green')
```
You'll have green screen applied result.
