### ISSUE TITLE
is a non Non Jit Version available

### ISSUE THREAD

**Issue by Satyaexp** [plemeri/transparent-background#55]
The current app i am working on works fine with the core Inspyrenet codebase and datasets, as discussed before there were issues in a few images where bodies were getting cut. Your suggestion to use base-nightly ckpt works fine with those images. the only precondition is to use JIT. is there a version without JIT that can do the same

**Comment by plemeri** [comment]
Yes you can if you modify just a little bit. comment out below lines and install locally.
https://github.com/plemeri/transparent-background/blob/b503b70ed8be04a8f67314605b26f840d4366a9a/transparent_background/Remover.py#L120-L123
