### ISSUE TITLE
transparent-background is the best library of image segmentation i've used so far, please keep upgrading!

### ISSUE THREAD

**Issue by mikebilly** [plemeri/transparent-background#61]
transparent-background beats birefnet, mvanet, unet,... in my use cases, only being inferior in very few cases. Please keep improving and creating better models! Thank you so much!
I'm currently using transparent-background, "[Plus_Ultra](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra.yaml)" and base-nightly

**Comment by VINTX2** [comment]
Totally agree with you. It is even better than the "hyped" rmbg-1.4.
Thank you for sharing the models you use. base-nightly seems to be better for some pictures.

**Comment by plemeri** [comment]
Thank you for enjoying our project!
