### ISSUE TITLE
[W NNPACK.cpp:53] Could not initialize NNPACK! Reason: Unsupported hardware

### ISSUE THREAD

**Issue by jaysheth9032** [plemeri/transparent-background#7]
I got this error in Ubuntu 18.04 I have also tried to install NNPACK but it still gives the error when --fast is not passed. But with --fast it is working fine.

**Comment by jaysheth9032** [comment]
Hi

Thanks for your reply. Here is the screenshot of terminal.

![image](https://user-images.githubusercontent.com/13344961/215389766-c286e470-75db-4fe1-8602-3a2f14a98537.png)

**Comment by plemeri** [comment]
As shown on the terminal, it failed to load GPU resource.
```
Settings -> Mode=base, Device=cpu, Torchscript=disabled
```
Can you check your system's GPU device whether it is properly working?

**Comment by jaysheth9032** [comment]
Sorry for asking this as i am not familiar with GPU can you tell me how check this whether It is available or not? Also if it is not there then how to install it or how to get it on my system?

Thanks

**Comment by plemeri** [comment]
Do you have installed any GPU on your system? Any specific model name or something?

**Comment by jaysheth9032** [comment]
I dont know how to check this

**Comment by plemeri** [comment]
I can help with your environment whether the CUDA backend is available or not. Try this script on python interpreter.
```python
import torch

print(torch.cuda.is_available())
```

If the result is false, it means your system is not working properly.

**Comment by jaysheth9032** [comment]
![image](https://user-images.githubusercontent.com/13344961/215395593-3d09c812-52aa-4a6b-8eab-492f47fc83eb.png)

Above image shows the graphic info

**Comment by jaysheth9032** [comment]
> ```python
> import torch
> 
> print(torch.cuda.is_available())
> ```

Hi @plemeri 

It returns false so it means no GPU is supported in my system.

Would I resolve this error after adding GPU device in my system?

**Comment by plemeri** [comment]
Installing nvidia GPU will resolve the issue.
