### ISSUE TITLE
video bitrate

### ISSUE THREAD

**Issue by zhouzhenneng** [plemeri/transparent-background#70]
When I used the transparent-background tool to process a green screen video, the source video had the following properties:

	•	Duration: 00:00:14.85
	•	Start: 0.000000
	•	Bitrate: 8768 kb/s

However, the resulting output video had these properties:

	•	Duration: 00:00:14.85
	•	Start: 0.000000
	•	Bitrate: 3353 kb/s

As you can see, the bitrate of the output video has been significantly reduced, leading to a decrease in video quality. How can I set a higher bitrate or maintain the original bitrate during processing?

**Comment by plemeri** [comment]
Hi @zhouzhenneng, I'll check if I can do for the bitrate problem in the next release. Sadly, I have no room for the update right now.

**Comment by zhouzhenneng** [comment]
Hi,

Taehun Kim ***@***.***> 于2024年7月30日周二 17:05写道：

**Comment by plemeri** [comment]
Hi, @zhouzhenneng, I changed the bitrate option in opencv videowriter, but this will not guarantee 100% identical bitrate as the input. If you still need the bitrate to be preserved, please save video as images and process each frame, then merge them into video format.
