### ISSUE TITLE
Dependencies don't reflect all that are required

### ISSUE THREAD

**Issue by kwokster10** [plemeri/transparent-background#73]
Hi all, I am currently using this package to remove background on images using the default setting, e.g.:

`out = remover.process(img) # default setting - transparent background`

[The Dependencies](https://github.com/plemeri/transparent-background?tab=readme-ov-file#dependencies-python-packages) however don't actually list all the ones that are required.

In addition to the ones listed these ones also appear required:
networkx==3.1
nvidia-cudnn-cu12
nvidia-cufft-cu12
nvidia-curand-cu12
nvidia-cusolver-cu12
nvidia-cusparse-cu12
nvidia-nccl-cu12
nvidia-nvtx-cu12

We aren't using the package with GPU so am wondering if there is a way for some of these dependencies to not be required.  Perhaps there's a way to do `pip install transparent-background[gpu]` for those that need all of that support. The addition of all of those packages greatly increases the amount of disk space required, which could deter others from using this awesome package.

**Comment by plemeri** [comment]
Hi @kwokster10, I actually thought of removing the dependencies for the gpu support externally, but most users usually want gpu support, so if you want to remove those gpu related packages, please remove torch and torchvision and reinstall the cpu only version after installing our package. 

* If you are on Windows
```bash
pip install transparent-background
pip uninstall torch torchvision torchaudio
pip install torch torchvision torchaudio
```
* If you are on Linux
```bash
pip install transparent-background
pip uninstall torch torchvision torchaudio
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
```

Thank you for your understading.

**Comment by kwokster10** [comment]
Thanks @plemeri for the response. I got it working with the suggested `--index-url https://download.pytorch.org/whl/cpu` after I had also specified `networkx==3.1` for Python 3.8.x.  While testing it out, I noticed it tries to write to `/var/www/.transparent-background` even though I'm not calling save on the final processed image. Why does it need to do that?

**Comment by plemeri** [comment]
Seems like you're working with the web server. It usually creates `.transparent-background` folder under the home directory, but in your case, its `/var/www`. If it's a problem such as permission issue, I think you might want to modify some of the source code and try to manually install the package. You can start from the hard-coded download path https://github.com/plemeri/transparent-background/blob/00f06d77a978361c66099458b4b73c45ebfd1b22/transparent_background/Remover.py#L43

**Comment by kwokster10** [comment]
What does it create the directory for though?  Is it for a custom config.yaml, and to determine where to store files if we save? I can fork this and edit, but would it be cleaner to set this up via a config variable that the user can set, and that can be added to the docs?

**Comment by kwokster10** [comment]
@plemeri if you agree with one of those above approaches, I'd be happen to open a PR with the change. Thanks!

**Comment by kwokster10** [comment]
@plemeri I hope you'll consider merging PR: https://github.com/plemeri/transparent-background/pull/75 and putting releasing a new minor version.
Thanks!
