### ISSUE TITLE
Allow other image formats (JPG)

### ISSUE THREAD

**Issue by DarkEyeDragon** [plemeri/transparent-background#78]
It would be helpful if we could specify what format we want to save as (defaulting to PNG)
In general PNG is fine but when using a solid background it's more space efficient to use JPG.

And frankly the software we use to process our images after expects JPG. So now i need to convert them first with FFMPEG before they're picked up.

**Comment by plemeri** [comment]
Hi @DarkEyeDragon, thanks for mentioning it. I'll consider adding options for output format including jpeg.

**Comment by plemeri** [comment]
@DarkEyeDragon Output format option is implemented for cli, API and gui. Please check out. Also, the default output format is now following the input format, so without specifying the output format, it'll follow the input format.
