### ISSUE TITLE
[Remover.py] what does the "threshold" means?

### ISSUE THREAD

**Issue by sanghyun0927** [plemeri/transparent-background#8]
First of all, Special thanks for making such a great model.

1. Can you define the meaning of "threshold"?

```
CONFIG = {
'base':     {'url': "https://drive.google.com/file/d/13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY/view?usp=share_link",
             'md5': "d692e3dd5fa1b9658949d452bebf1cda",
             'base_size': [1024, 1024],
             '**threshold**': None,
             'ckpt_name': "ckpt_base.pth",
```

2. Can you suggest any post processing method for deleting blurry parts around boundary?

**Comment by plemeri** [comment]
Hello Sanghyun,

Let me briefly explain about this pypi package. It is built upon our work [InSPyReNet](https://github.com/plemeri/InSPyReNet). 

We targeted High-Resolution prediction without using HR datasets. For this purpose, we proposed pyramid blending, and we use `threshold` parameter to deal with different image sizes.

However, with HR datasets, our model can work even better thanks to the image pyramid structure itself, so we released this pypi package trained with HR datasets. In this case, pyramid blending is not needed, so we set `threshold` as `None`.

And for the second question, I think [CascadePSP](https://github.com/hkchengrex/CascadePSP) can help for removing noises.
