### ISSUE TITLE
Can you remove the foreground and keep the background

### ISSUE THREAD

**Issue by sobermh** [plemeri/transparent-background#81]
First of all, thank you for your contribution, this is a very good library, to solve my problem of removing the video background, thank you very much, but if I want to reverse the function, remove the foreground, preserve the background, can the code now be implemented

**Comment by plemeri** [comment]
Hi @sobermh, sure, it's very easy to do so. I'll add it for the next release.

**Comment by sobermh** [comment]
> Hi @sobermh, Thank you for your reply, may I ask when, because I recently very need to find a function

**Comment by sobermh** [comment]
> Hi @sobermh, sure, it's very easy to do so. I'll add it for the next release.

Thank you for your reply, may I ask when, because I recently very need to find a function

**Comment by plemeri** [comment]
@sobermh I can only spare some time in the weekends.

**Comment by sobermh** [comment]
@plemeri  i got you！ Thanks again

**Comment by sobermh** [comment]
> @sobermh I can only spare some time in the weekends.

 i got you！ Thanks again！

**Comment by plemeri** [comment]
@sobermh `reverse` option is implemented for API, cli and gui in the latest release. Please check out.

**Comment by karmelyoei** [comment]
> @sobermh `reverse` option is implemented for API, cli and gui in the latest release. Please check out.

which version? I don't see it

**Comment by sobermh** [comment]
> @sobermh `reverse` option is implemented for API, cli and gui in the latest release. Please check out.

thanks again! I'll try it later

**Comment by sobermh** [comment]
> > @sobermh `reverse` option is implemented for API, cli and gui in the latest release. Please check out.
> 
> which version? I don't see it

maybe the latest version， I see it in usage  ， --reverse
