### ISSUE TITLE
NameError: name 'Loader' is not defined

### ISSUE THREAD

**Issue by goglocal123** [plemeri/transparent-background#9]
Installed package using pip install transparent-background.

Python Version: 3.8
OS: Ubuntu 20.04 (WSL)

Command Executed: transparent-background --source <image-path>
Error occurred:
![image](https://user-images.githubusercontent.com/102602352/217253963-7bf1f8f2-0243-40a8-91b2-031955e75fa0.png)

**Comment by plemeri** [comment]
Hi, the error occured because of the unsupported image format. jfif format is not supported in this package. Please used jpg or png format instead.

Thanks
